name: Build Windows Executable

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Quick syntax check
        run: python -m py_compile swamp_reconnect.py

      - name: Build executable
        run: pyinstaller --onefile --name SwampReconnect swamp_reconnect.py
        # If you prefer the default name, remove --name and change the artifact path below

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwampReconnect-windows
          path: dist/SwampReconnect.exe
          if-no-files-found: error
